apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "dimo-oracle.fullname" . }}-secret
  namespace: {{ .Release.Namespace }}
spec:
  data:
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/db/host
    secretKey: DB_HOST
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/db/user
    secretKey: DB_USER
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/db/pass
    secretKey: DB_PASSWORD

  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/walletAddress
    secretKey: DEVELOPER_AA_WALLET_ADDRESS
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/walletPk
    secretKey: DEVELOPER_PK
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/rpcUrl
    secretKey: RPC_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/bundlerUrl
    secretKey: BUNDLER_URL
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/authPk
    secretKey: DIMO_AUTH_PRIVATE_KEY
  - remoteRef:
      key: {{ .Release.Namespace }}/dimo-oracle/sdWalletSeed
    secretKey: SD_WALLETS_SEED
  - remoteRef:
      key: {{ .Release.Namespace }}/connections/dimo-oracle/cert
    secretKey: CERT
  - remoteRef:
      key: {{ .Release.Namespace }}/connections/dimo-oracle/key
    secretKey: CERT_KEY
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secretsmanager-secret-store
  target:
    name: {{ include "dimo-oracle.fullname" . }}-secret
    template:
      metadata: {}
